In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x.ndim) # 1
print(x.shape) # (3, )

# element-wise operation
print (x + y) 
print (x * y)

# broadcasting
print(x * 3)
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(a * b)

# 내적과 행렬곱
## 내적
print(np.dot(x, y))
## 행렬곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.matmul(A, B))

In [1]:
import numpy as np

x = np.array([1, 2, 3]) # 1차원 ndarray에서 axis는 0뿐임.
print(np.sum(x, axis=0))

y = np.array([[1, 2, 3], [4, 5, 6]]) # 2차원 ndarray에서 axis=0은 행방향, axis=1은 열방향을 가리킴
print(np.sum(y, axis=0))
print(np.sum(y, axis=1))

# 자 이제 어떻게 할래? 
z = np.arange(24).reshape(2,3,4)
print(z)
print(np.sum(z, axis=0))
print(np.sum(z, axis=1))
print(np.sum(z, axis=2))

6
[5 7 9]
[ 6 15]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


사실, ndarray의 경우 axis(n)을 행렬의 실제 축으로 이해할 필요가 없음
만약, ndarray(A)가 3차원일 경우 A[i][j][k] 형태의 3차원 배열로 구성되어 있을텐데 여기서 axis0 = i, axis1 = j, axis2 = k 이렇게 순서대로 매겨짐
즉, A[i][j]라면 동일하게도 axis0=i, axis1=j임. 이건 달라지지가 않는다.
만약에서, np.sum(A, axis=0)을 실행하면 이 말은 $$\Sigma_{i} A[i]$$ 를 하라는 말로 이해하도록 하자