In [ ]:
# Linear Transformation
import numpy as np

batch_size = 3
x = np.random.randn(batch_size, 2)
W1 = np.random.randn(2, 4)
b = np.random.randn(4)

h = np.matmul(x, W1) + b
print(h)

In [ ]:
# Non-Linear Transformation : 신경망의 표현력 높이기
def sigmoid(x) : 
	return (1 / 1 + np.exp(-x)) # 1/(1 + e^{-x})
a = sigmoid(h) # 실제 뉴런층의 출력

In [ ]:
# Inference Code without abstraction
import numpy as np

batch_size = 3
x = np.random.randn(batch_size, 2) # input data
W1 = np.random.randn(2, 4) # hidden Layer Weight
b1 = np.random.randn(1, 4) # hidden Layer Bias
W2 = np.random.randn(4, 3)
b2 = np.random.randn(1, 3)

h1 = np.matmul(x, W1) + b1
a1 = sigmoid(h1)
s = np.matmul(a1, W2) + b2 # : Score를 의미(확률로 변환되기 이전의 값)

In [4]:
import numpy as np

class Affine :
	def __init__(self, W, b) :
		self.params = [W, b]

	def forward(self, x) :
		W, b = self.params
		return (np.matmul(x, W) + b)
	
class Sigmoid :
	def __init__(self) :
		self.params = []
	
	def forward(self, x) :
		return (1 / (1 + np.exp(-x)))

class TwoLayerNet :
	def __init__(self, input, hidden, output) :
		I, H, O = input, hidden, output
		W1 = np.random.randn(I, H) # hidden Layer Weight
		b1 = np.random.randn(1, H) # hidden Layer Bias
		W2 = np.random.randn(H, O)
		b2 = np.random.randn(1, O)

		# 계층들을 하나의 리스트로 만들어서 사용하기 쉽도록 구성
		self.layers = [
			Affine(W1, b1),
			Sigmoid(),
			Affine(W2, b2)
		]

		# 각 계층들의 매개 변수를 한 곳에 모아둠 : 역전파시 업데이트가 쉬워진다.
		self.params = []
		for layer in self.layers :
			self.params.append(layer.params) # <=> self.params += layer.params

	def predict(self, x) :
		for layer in self.layers :
			x = layer.forward(x)
		return (x)

batch_size = 3
x = np.random.randn(batch_size, 2) # input data
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

print(s)

[[2.18547451 0.94792268 1.18453928]
 [2.17658057 0.95215502 1.11946348]
 [2.15456156 0.93663638 0.48049644]]
